<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Descripcin</name>
   <tag></tag>
   <elementGuidId>d3acc85d-f5e1-4976-9b76-ca2a48b357ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/article/header/div/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.toc-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>605d6326-85ab-48ff-9b89-adf7a7d27273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toc-title</value>
      <webElementGuid>aa5b0c94-cdf0-496f-afeb-a627159cb756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descripción</value>
      <webElementGuid>53b2d16b-8ee0-4814-bcd0-d73393881c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[1]/header[1]/div[@class=&quot;table-of-contents&quot;]/ul[1]/li[1]/a[@class=&quot;toc-main-link&quot;]/span[@class=&quot;toc-title&quot;]</value>
      <webElementGuid>a43ac0ff-7411-4532-97e8-bda053928bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/article/header/div/ul/li/a/span[2]</value>
      <webElementGuid>725f24a7-383d-4670-8fb3-af061e853180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[2]/following::span[2]</value>
      <webElementGuid>42b6abf7-a022-4814-b971-8784783c92e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ejemplos'])[1]/preceding::span[2]</value>
      <webElementGuid>f2b77a89-88d4-49d6-ad66-3f035f118c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atributos'])[1]/preceding::span[4]</value>
      <webElementGuid>97191b5a-9f03-4b50-a862-a8633eddcfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descripción']/parent::*</value>
      <webElementGuid>e7b956ea-bcea-453f-893f-44785c45f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>a8166a3b-4fe4-48a9-b89b-adff89156f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Descripción' or . = 'Descripción')]</value>
      <webElementGuid>5b1e3340-9420-439a-96c4-529bd8356fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
