<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acceptable</name>
   <tag></tag>
   <elementGuidId>cc97ebb5-befe-452a-949f-8aff72648773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acceptable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acceptable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c6a59db-e85e-432f-ac73-787191071999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptable</value>
      <webElementGuid>6caf17ee-1308-4d81-a171-ef1b22d748da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box mt-4 ui-draggable ui-draggable-handle</value>
      <webElementGuid>d0242054-8ca5-40fa-ba30-9e36410dae44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acceptable</value>
      <webElementGuid>34f771e9-49a8-43dc-bb0c-661c364281bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptable&quot;)</value>
      <webElementGuid>23ed27fa-0316-462f-a6c6-3ad3b1d3085f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='acceptable']</value>
      <webElementGuid>e4012ff4-28d3-4033-9ae0-ab9192dddc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acceptDropContainer']/div/div</value>
      <webElementGuid>1c150496-b758-4add-9e27-4762ef81c671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[5]</value>
      <webElementGuid>3ff28a84-8a9b-409b-99be-cafa1fe5ced0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[13]</value>
      <webElementGuid>0dc8adbc-0cf9-4f82-9d7c-1af98648fa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag Me'])[1]/preceding::div[3]</value>
      <webElementGuid>e790aa19-d40a-41c0-b113-32d1235c6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acceptable']/parent::*</value>
      <webElementGuid>2944b323-dc85-4e0a-b8f1-16a3dd3067de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>adb15a9e-9cd0-4e21-8ec9-708b56d3ea3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'acceptable' and (text() = 'Acceptable' or . = 'Acceptable')]</value>
      <webElementGuid>69bc4c3c-ef45-40bf-83ab-5d48d8b0a3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
