<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ftbol      Crquet      Bsquetbol    _80b0d8</name>
   <tag></tag>
   <elementGuidId>65b8971b-e2da-4800-b362-9ece76759438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='deporte']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;deporte&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>28a6cddc-6803-44fd-a5e4-d024841af607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deporte</value>
      <webElementGuid>b9ad166a-c285-44a7-84bf-46dda044476b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Fútbol
      Críquet
      Básquetbol
      Hockey
      Tenis
    </value>
      <webElementGuid>96244aa1-b2b1-4a0a-9989-c20486b08127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;examples&quot;)/div[@class=&quot;code-view&quot;]/div[@class=&quot;code-view-lines&quot;]/form[1]/p[1]/select[1]</value>
      <webElementGuid>fec9f165-2552-4a2a-b8c9-b3c696bd91ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='deporte']</value>
      <webElementGuid>e96a117e-6258-46b0-ac96-2663c247f548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='examples']/div/div/form/p/select</value>
      <webElementGuid>2d2838e6-b278-4398-882a-839c2d27a104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;/form>'])[1]/following::select[1]</value>
      <webElementGuid>94e47488-5c64-4529-84d1-bfc4ec382c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;/p>'])[1]/following::select[1]</value>
      <webElementGuid>87e53baf-b2f4-496f-ad66-2646c9e02a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='value'])[3]/preceding::select[1]</value>
      <webElementGuid>09f63548-7519-4620-ac2a-12da05f2cca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option'])[5]/preceding::select[1]</value>
      <webElementGuid>01d8e36a-8d4d-4eda-a625-1bef80c101e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0e9308fd-4774-491e-91b9-750823b6666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'deporte' and (text() = '
      Fútbol
      Críquet
      Básquetbol
      Hockey
      Tenis
    ' or . = '
      Fútbol
      Críquet
      Básquetbol
      Hockey
      Tenis
    ')]</value>
      <webElementGuid>f38ad578-c24b-4485-be6b-9891efc02133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
