<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maven</name>
   <tag></tag>
   <elementGuidId>93b5a962-92bd-45d4-aca2-c74aaa274450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-collapse']/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f357da9-330d-4daa-b191-a6e330e8e06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/maven-tutorials</value>
      <webElementGuid>6dfad854-9d00-425c-8875-a2b1ea87638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maven</value>
      <webElementGuid>7f218d6a-a5b2-444b-9d37-cfaa5cacda74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-collapse&quot;)/nav[1]/ul[@class=&quot;menu nav navbar-nav&quot;]/li[@class=&quot;leaf&quot;]/a[1]</value>
      <webElementGuid>ab78b0b4-e439-4059-adc6-4d2a96e001f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-collapse']/nav/ul/li[4]/a</value>
      <webElementGuid>6a8d07b8-36ef-4ab5-ab41-5c156a705b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Maven')]</value>
      <webElementGuid>893e59b8-8641-4363-a284-bdcea0b6f7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestNG'])[1]/following::a[1]</value>
      <webElementGuid>a2c2f2e8-80b7-421d-9ecc-a34a10839ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium with Python'])[1]/following::a[2]</value>
      <webElementGuid>9d3b3ab6-9f18-4c7b-b027-e6cf0a2b6fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenkins'])[1]/preceding::a[1]</value>
      <webElementGuid>e957dcd6-359e-4f2a-9fdd-4c7d3f7317a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protractor'])[1]/preceding::a[2]</value>
      <webElementGuid>6a0322a4-fc7f-41a9-ab92-e547c808dde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maven']/parent::*</value>
      <webElementGuid>e96b7313-f716-4d06-a01f-4da67e824cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/maven-tutorials')]</value>
      <webElementGuid>ea8eca8e-d3ba-4b3c-923f-6d75d1c9770c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>3bf2e61e-1a3f-4751-b28c-eda95709fe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/maven-tutorials' and (text() = 'Maven' or . = 'Maven')]</value>
      <webElementGuid>4bc9dbf3-dcc9-41d0-94b2-d5aacbaf9721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
