<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d233633f-1a21-45ad-9593-ad0ece9c5bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7423e7cd-ece9-4ee7-b2aa-220167625a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/image/cache/catalog/demo/macbook_2-74x74.jpg</value>
      <webElementGuid>4e800e95-96d6-447e-9ca3-bfaee97a1e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>ac901bac-f994-4dde-b6a7-4c1d9122615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>d9eff800-874c-48b4-8e5d-66900ae31d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>1164130264</value>
      <webElementGuid>c6acfd50-d173-46ec-a3ad-7693f147aa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>4b781d54-3694-4af1-b40a-8def0c562806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/ul[@class=&quot;thumbnails&quot;]/li[@class=&quot;image-additional&quot;]/a[@class=&quot;thumbnail&quot;]/img[1]</value>
      <webElementGuid>84e5ae18-2150-47c8-be62-dc8a0207624e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      <webElementGuid>4cb55d34-df7f-4265-934c-0acf2aded80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='MacBook'])[4]</value>
      <webElementGuid>4b3b82ea-4584-4ec6-93aa-54ccf8fd8471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>7181666f-7016-4b2f-b601-96075edeae66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://opencart.abstracta.us:80/image/cache/catalog/demo/macbook_2-74x74.jpg' and @title = 'MacBook' and @alt = 'MacBook']</value>
      <webElementGuid>51e420da-ce99-4d37-ab80-f2d370caea86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
