<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What type is it_filetype</name>
   <tag></tag>
   <elementGuidId>b5ca89bd-27e6-4a1d-b7f6-113e1279b16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsanimage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itsanimage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e1ecfa1-fc99-4803-a354-f81a2185e74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fb67ecf9-5d29-4de3-9186-0c8d7d7c9c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsanimage</value>
      <webElementGuid>61505342-38cd-4369-b0cf-d50eeba55971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filetype</value>
      <webElementGuid>fa33a238-9523-45e2-9029-f484dda987c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>d9432912-67cb-4d39-86a9-2defb9628221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsanimage&quot;)</value>
      <webElementGuid>fd82ab53-ce54-4373-8f78-9fdd919fe1c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsanimage']</value>
      <webElementGuid>390a488f-3619-431a-8d73-d02385ec2ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c2d65ce9-964f-4de8-89e5-5607bdeee353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'itsanimage' and @name = 'filetype']</value>
      <webElementGuid>6c83f431-9e3d-4572-803e-71b28d95f3d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
