<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_report</name>
   <tag></tag>
   <elementGuidId>80a421a0-ce85-4318-91ca-41bd87ec27f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='node-281']/footer/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.field-item.even > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d038882a-7622-4709-9cac-60c7845fa07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tags/report</value>
      <webElementGuid>e8dba66a-8f03-4085-a6ad-b8d5d0338a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeof</name>
      <type>Main</type>
      <value>skos:Concept</value>
      <webElementGuid>44c79360-86ce-4375-8a56-b1ede5441c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>rdfs:label skos:prefLabel</value>
      <webElementGuid>645efbfb-ce65-4cfe-8e9d-65debefd2faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>report</value>
      <webElementGuid>02e46a13-8d29-4f0a-8e40-00e4ea749c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node-281&quot;)/footer[1]/div[@class=&quot;field field-name-field-tags field-type-taxonomy-term-reference field-label-above&quot;]/div[@class=&quot;field-items&quot;]/div[@class=&quot;field-item even&quot;]/a[1]</value>
      <webElementGuid>140612c4-3717-4d79-83ba-2ab3a9e2e37e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='node-281']/footer/div/div[2]/div/a</value>
      <webElementGuid>cb5e1a76-cd2e-4e21-86f3-e4bceb06b4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'report')]</value>
      <webElementGuid>58df247a-00b5-41b7-8f35-67039ab0aafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='harrydev'])[1]/following::a[1]</value>
      <webElementGuid>f2fec445-752f-4296-9b20-f581ae09fb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestNG Report'])[1]/preceding::a[1]</value>
      <webElementGuid>0440c172-4e32-421e-8e4c-e09830f20e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='report']/parent::*</value>
      <webElementGuid>36040cde-d084-405f-bda3-862d480e9808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tags/report')]</value>
      <webElementGuid>8f691480-ab95-4109-9989-a72aae1f30d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]/div/a</value>
      <webElementGuid>4085fc40-09e7-4594-9a2e-f46808bb2c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tags/report' and (text() = 'report' or . = 'report')]</value>
      <webElementGuid>bc419948-1d26-461c-954c-53c5a0a9c264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
