<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin_direccion</name>
   <tag></tag>
   <elementGuidId>0e2d924b-62e6-4a2f-a5c5-63b0f6069ada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='direccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;direccion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>183a4e58-4e77-42dc-b10a-6145d5bcbb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a5d9767-e0db-4f18-ad2d-f4e8350d2121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>direccion</value>
      <webElementGuid>61687497-3f09-4bbd-ab42-6f240007438d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86fb98a0-3fe2-4516-934c-7516d00851c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección (Ej. Valdivia 101)</value>
      <webElementGuid>1021138f-99e8-4488-b3df-1d46f41bd758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e4d5d2a0-5a43-4314-8f5d-6e70bd752bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>54afc932-05c9-47a4-898d-357d3b7119ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9-áÁéÉíÍóÓúÚ- ]{1,30}</value>
      <webElementGuid>f1414948-2f0b-4660-b3d9-bc5afe4e06c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/p[4]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>813eb88a-2ece-40ef-9c49-7f630cb4577c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='direccion']</value>
      <webElementGuid>988f01a9-ca0b-4540-8d1a-4c2e491ed4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>bca6f9de-cc1c-4642-8a08-5e25aea53590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'direccion' and @placeholder = 'Dirección (Ej. Valdivia 101)']</value>
      <webElementGuid>6aa1e3af-f4a9-4d99-854b-9ad3405bccf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
