<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciudad_ciudad</name>
   <tag></tag>
   <elementGuidId>86d624f9-b4e9-4f55-972d-833b9a6e7c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ciudad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ciudad&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51b063e6-0f32-4533-9e5e-4109697fb191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b9f7b35-63ac-479d-b312-4c5ffd9160ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ciudad</value>
      <webElementGuid>110d1f1b-2782-4f1d-bda8-d1f0d0d1d0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b95fc9f-a259-483a-9282-51a3e4cdf6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej. Santiago</value>
      <webElementGuid>0546fbfe-6e13-4ea3-a4f9-a3b04921851d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>40e1df20-bb1d-4f24-ab53-aed200d83162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6ec8e6a6-565a-4c1b-9800-23f955998b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[A-Za-z-áÁéÉíÍóÓúÚ ]{1,30}</value>
      <webElementGuid>107174ca-a49a-41be-81c4-7b179bf02ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/p[5]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>a8304c08-7f4d-42b6-a542-48f26e1d8c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ciudad']</value>
      <webElementGuid>3ccddd2a-dd8d-49b5-bfe3-0a699cd20eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>15b167d3-c8e7-46bc-b29e-d2feeb8a3332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ciudad' and @placeholder = 'Ej. Santiago']</value>
      <webElementGuid>d63a9e63-a40e-423f-ba9a-aa3957c52892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
