<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comentarios_comentario</name>
   <tag></tag>
   <elementGuidId>8ca2a71d-9ac2-4b45-be94-7bf2303112a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='comentario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;comentario&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d09a65ac-8730-464e-81ab-7186435b1739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>811c7a2a-f0e6-4df3-9d1c-88c397cb64f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comentario</value>
      <webElementGuid>5fcf01f1-0a48-4472-9e38-e5122ab15004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1b4137d-70b9-41f8-8929-7ce6a1bff503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe brevemente en máximo 300 carácteres.</value>
      <webElementGuid>89a5becb-4549-49ba-9441-442aba38c2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>fcd87ca0-60f6-42f8-a038-f0810d37a87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9-áÁéÉíÍóÓúÚ-. ]</value>
      <webElementGuid>d1e04a52-3498-4583-9be7-0a17833ae5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/p[10]/label[1]/label[1]/textarea[@class=&quot;input&quot;]</value>
      <webElementGuid>c7cf965b-617b-4332-96f3-d66e27fca883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='comentario']</value>
      <webElementGuid>abcb103c-5f9e-47a4-b6ad-eed0d00a318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2766a8ff-ba32-4164-84d8-3ce90d7cd94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @name = 'comentario' and @placeholder = 'Describe brevemente en máximo 300 carácteres.']</value>
      <webElementGuid>97c89327-545e-4b0c-a49b-a2b9ff195877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
