<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Finalizar compra</name>
   <tag></tag>
   <elementGuidId>8aa457a5-5d91-416b-89de-3cb1cba62d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-to-orderform']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-to-orderform</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aec6ecc7-2b2c-4fb2-b7d7-b14e3bc0f314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/orderform</value>
      <webElementGuid>e591b874-4c6f-442f-8af4-291b8c676842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>aa2cd378-526d-4a9e-ae14-83e6e659c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>cartToOrderform</value>
      <webElementGuid>4b5a7556-2219-4846-b7d6-36af59d4a0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-to-orderform</value>
      <webElementGuid>62b4fdf4-b198-46a0-a044-923a4c8b59b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-large btn-success pull-left-margin btn-place-order</value>
      <webElementGuid>a035da66-89c1-4369-acd7-ec5eb8ecb59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>cart.finalize</value>
      <webElementGuid>66b53cab-aa48-46cf-977d-a9e47ca74f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: cart.next</value>
      <webElementGuid>64a0d327-7469-4cf0-bd29-341f6837fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar compra</value>
      <webElementGuid>84482748-c3c6-4be1-ab8c-0e0cde974fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutMainContainer&quot;)/div[@class=&quot;container container-main container-cart&quot;]/div[@class=&quot;checkout-container row-fluid cart-active&quot;]/div[@class=&quot;cart-template full-cart span12 active&quot;]/div[@class=&quot;summary-template-holder&quot;]/div[@class=&quot;row-fluid summary&quot;]/div[@class=&quot;span5 totalizers summary-totalizers cart-totalizers pull-right&quot;]/div[2]/div[@class=&quot;accordion-group&quot;]/div[@class=&quot;accordion-body collapse in&quot;]/div[@class=&quot;accordion-inner&quot;]/table[@class=&quot;table&quot;]/tfoot[@class=&quot;total-cenco&quot;]/span[@class=&quot;btn-place-order-wrapper&quot;]/a[@id=&quot;cart-to-orderform&quot;]</value>
      <webElementGuid>24e3a130-149c-4e26-9145-875ac570b152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-to-orderform']</value>
      <webElementGuid>df3dd7b4-73a2-42f2-b898-9e520ba8d88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='checkoutMainContainer']/div[4]/div[3]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/table/tfoot/span/a</value>
      <webElementGuid>88b6626f-4575-4ec7-889c-e22ef6913339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Finalizar compra')]</value>
      <webElementGuid>c0a7873c-a5f5-4b43-ab7e-c961e4591eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 49.990'])[5]/following::a[1]</value>
      <webElementGuid>14cc4010-9643-439b-b846-37349825bc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/following::a[1]</value>
      <webElementGuid>7ea4b192-13b1-4d48-a515-d8b26450232d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegir más productos'])[1]/preceding::a[1]</value>
      <webElementGuid>aea0fccc-c9ae-4188-ba7f-d6625d36cf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprimir'])[1]/preceding::a[2]</value>
      <webElementGuid>20a5b306-7d4d-40f0-a196-e5cbffb82550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar compra']/parent::*</value>
      <webElementGuid>bc456577-cca9-4764-ad59-a4e85ef8f752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/orderform')]</value>
      <webElementGuid>3a15af50-346a-485e-ae36-4626df3f827f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/span/a</value>
      <webElementGuid>cb9785f7-714f-4ed1-9225-ee405939603b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/orderform' and @id = 'cart-to-orderform' and (text() = 'Finalizar compra' or . = 'Finalizar compra')]</value>
      <webElementGuid>7cbbcbff-0bbd-4666-9b91-da95ba76854a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
